### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by patrickdk77** [danielglejzner/ngx-maintenance#12]
How do we use this repository, the instructions do not function for me.

npm install @ngx-maintenance/ng2-search-filter --save

npm ERR! code 127
npm ERR! path /projects/node_modules/@ngx-maintenance/ng2-search-filter
npm ERR! command failed
npm ERR! command sh -c npx ngx-maintenance warn ng2-search-filter
npm ERR! sh: 1: ngx-maintenance: not found

npm ERR! A complete log of this run can be found in: /home/node/.npm/_logs/2024-04-06T00_34_47_304Z-debug-0.log

0 verbose cli /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@10.5.0
2 info using node@v18.20.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 5ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:/projects/node_modules/@ngx-maintenance/ng2-search-filter/.npmrc Completed in 0ms
10 timing config:load:project Completed in 11ms
11 timing config:load:file:/home/node/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 2ms
16 timing config:load Completed in 25ms
17 timing npm:load:configload Completed in 25ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm exec ngx-maintenance warn ng2-search-filter
22 verbose argv "exec" "--" "ngx-maintenance" "warn" "ng2-search-filter"
23 timing npm:load:setTitle Completed in 2ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/home/node/.npm/_logs/2024-04-06T00_34_51_585Z-
26 verbose logfile /home/node/.npm/_logs/2024-04-06T00_34_51_585Z-debug-0.log
27 timing npm:load:logFile Completed in 10ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 58ms
31 silly logfile start cleaning logs, removing 1 files
32 silly logfile done cleaning log files
33 timing arborist:ctor Completed in 1ms
34 http fetch GET 200 https://registry.npmjs.org/ngx-maintenance 195ms (cache revalidated)
35 timing arborist:ctor Completed in 0ms
36 timing arborist:ctor Completed in 1ms
37 timing arborist:ctor Completed in 0ms
38 timing command:exec Completed in 729ms
39 verbose exit 127
40 timing npm Completed in 1011ms
41 verbose code 127

**Comment by Jordan-Hall** [comment]
I'll push a fix out later sorry. It appears npx ngx-maintenance warn ng2-search-filter not found. This is a CLI for a post install message https://www.npmjs.com/package/ngx-maintenance

**Comment by Jordan-Hall** [comment]
Found, ill push a fix in morning. I believe https://github.com/danielglejzner/ngx-maintenance/blob/main/libs/ngx-maintenance isn't compiling correctly on NPM Package. It's pushing the ts file and not js. Sorry. It's 3am I'll fix when on laptop in morning

**Comment by patrickdk77** [comment]
No problem, I just wanted to comment before I lost my thoughts over the weekend. spent two days getting the upgrades done and all the dependencies only to find out I had this issue in a *single place* in my app :) half tempted to rip it out, but that takes time also

**Comment by Jordan-Hall** [comment]
Sorry I'll push a fix then add test in place. Will test the auto migration that comes with package too. 

I'll work on project documentation next week!

**Comment by Jordan-Hall** [comment]
Update we use NX release and its publishing the source folder not built sorry :( https://github.com/nrwl/nx/issues/21855 Fix will be done in morning.

**Comment by patrickdk77** [comment]
go too bed! I just thought I was doing something stupid and couldn't see past my nose :)

**Comment by Jordan-Hall** [comment]
Thanks for being understanding, think I've got a solution but will finish it in morning.

**Comment by Jordan-Hall** [comment]
@patrickdk77  that should now be fixed. Can you let me know if there any other issues. Sorry this is still in its infantry but we supporting them from get go. Nx release has some undocumented fix

**Comment by patrickdk77** [comment]
It works as expected, I do not see any issues :)
