### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Yberion** [danielglejzner/ngx-maintenance#3]
Hello @Jordan-Hall @danielglejzner,

This project/repo looks promising!

I have some questions:

- `[1]` Is the point of this repo to only migrate libs that are unmaintained and still View Engine or just unmaintained libs no matter if they are on Ivy or not?
  - If it is about unmaintained libs, no matter if they are Ivy or not (I think this is what I understood from the readme), then the readme could potentially be a bit missleading (mostly the title of the readme)
- `[2]` Is the plan to only migrate libs or it is planned to also maintain the demo-app associated with the lib?
- `[3]` Is there any threshold on when we can "decide" when a lib is unmaintained and can be "moved" on this repo?
  - Time without commit?
  - Time without release?
  - Number of download?
    - Might not be worth the time to migrate a lib with 5 downloads a month? (no idea)
  - Other?
- `[4]` Regarding `[3]`, do you think that it would be usefull to set some "rules"/"governance" on libs that are going to be "moved" here?
  - The point of this repo is to maintain libs that aren't anymore, but what if someone PR an update of a lib and it got accepted and this lib is no longer updated on this repo by the author of the PR? (which is fine tbh)
    - This will mean that if none update that lib on this repo, it will also be unmaintained on this repo as well, that's why I was talking about threshold, rules & co. If there's too much libs to maintain on this repo, we could face the same issue as on the original repo. All this could totally be fine as this is an open source contribution and none is obligated to do "anything".

**Comment by danielglejzner** [comment]
Hi @Yberion ! Thanks for the questions.

1. Yes, primary goal is to take care of view engine libraries to unblock companies. Right now Angular 15 is a hard stop for many. For the future once we fulfil the initial goal we can think about expanding the scope. 
2. Plan is only to upgrade unmaintained libs. We are not planing to do more then that. 
3. Good question, we need more data for this. For now we are gathering reports from people running `ngx ng16-dep-audit` and adding these libs manually. Later on we are going to automate the process. These libs are by nature unmaintained so it's hard to come up with a metric and we don't want to leave anybody stranded. 
4. It's going to be an automated process to keep everything constantly updated once it lands here. We are not planning to fix bugs, only upgrade the Angular version on these.

**Comment by Jordan-Hall** [comment]
I want to expand on the first point. The repo will handle all libview engines or ivy. The first focus is on view engine to be migrated but will accept any PR for ivy repos too

Daniel right We really don't want to be running demo apps. Unless we can secure an automated pull-in and deploy to a single site with documents and all demos for each,. Its not going to be planned (any time soon). We doing this to help migration process

**Comment by Yberion** [comment]
Thanks for the answers :)
